name: Verify services pipeline
on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: "1.24"
        description: Golang version
jobs:
  verify-services:
    name: Verify services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Golang
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go_version }}

      - name: Generate .env
        run: make generate/env

      - name: Generate go.work
        run: make generate/work

      - name: Run linters
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
          args: --timeout=5m ./backend/... ./device/... ./test/...
          skip-cache: true
          skip-save-cache: true
